### ISSUE TITLE
substring search across has_many field

### ISSUE THREAD

**Issue by morenoh149** [izimobil/django-rest-framework-datatables#104]
Hello, I am building a meeting application. We would like to filter people we have had meetings with (Experts) by historical Meeting objectives.

A minimal runnable example https://github.com/morenoh149/django-rest-datatables-relations-example

SO https://stackoverflow.com/questions/66286391/django-rest-datatables-search-across-relationships

These are the models
```
User = get_user_model()


class Expert(models.Model):
    name = models.CharField(blank=True, max_length=300)


class Meeting(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    expert = models.ForeignKey(Expert, on_delete=models.SET_NULL, blank=True, null=True)
    objective = models.TextField(null=True, blank=True)
```
the datatables javascript so far
```
  var table = $('#experts').DataTable({
    "serverSide": true,
    "ajax": "/api/experts/?format=datatables",
    "columns": [
      {"data": "id"},
      {"data": "name"},
      {"data": "objectives"}
    ]
  });
```
serializers
```
class ExpertSerializer(serializers.ModelSerializer):
    id = serializers.IntegerField(read_only=True)
    objectives = serializers.SerializerMethodField()

    class Meta:
        model = Expert
        fields = (
            'id', 'name', 'objectives'
        )
        datatables_always_serialize = ('id',)

    def get_objectives(self, obj):
        request = self.context["request"]
        meetings = Meeting.objects.filter(
            user_id=request.user.id, expert_id=obj.id
        ).distinct('objective')
        if len(meetings) > 0:
            objectives = meetings.values_list("objective", flat=True)
            objectives = ", ".join([x for x in objectives if x])
        else:
            objectives = []
        return objectives


class MeetingSerializer(serializers.ModelSerializer):
    id = serializers.IntegerField(read_only=True)

    class Meta:
        model = Meeting
        fields = (
            'id', 'objective',
        )
        datatables_always_serialize = ('id',)
```
the UI
![datatables-meeting-objectives](https://user-images.githubusercontent.com/587438/108880046-e2e0de80-75cf-11eb-8a5e-c629554b9767.PNG)

I don't care if the objectives are a SerializerMethodField, if some relationship traversal works that's fine too (something like `'data': 'expert.meeting_set.objectives'`).
How can we filter Experts by historical Meeting objectives?

**Comment by matthewhegarty** [comment]
hi Harry, I added a response to your SO question, and created a [`django-rest-framework-datatables`](https://stackoverflow.com/questions/tagged/django-rest-framework-datatables) tag.  It would be best to post questions on there, and then we can leave this for discussion of issues / bugs with the library.

**Comment by morenoh149** [comment]
@matthewhegarty adding a new tag to stackoverflow takes some time/rep. Can you help? https://stackoverflow.com/review/suggested-edits/28409419 the tag you added was removed, I tried readding it.

**Comment by morenoh149** [comment]
I ended up coming up with a solution in the stackoverflow and example. Hopefully it helps the community.
