### ISSUE TITLE
"Illegal mix of collations for operation 'like'" utf8 search error

### ISSUE THREAD

**Issue by giorgiberia** [izimobil/django-rest-framework-datatables#111]
when I try to search something other than ASCII backend throws this error. i followed the docs described and every other aspect works very well

**Comment by izimobil** [comment]
I think this is not related to DRF-datatables but just your database table encoding.

**Comment by giorgiberia** [comment]
database table encoding is utf8-general-ci

**Comment by izimobil** [comment]
I'm pretty sure this is not related to DRF-datatables, since we use standard Django filtering.
Did you see this article https://tableplus.com/blog/2019/08/illegal-mix-of-collations-mysql.html ? It may solve your problem.
