### ISSUE TITLE
Travis build not running

### ISSUE THREAD

**Issue by matthewhegarty** [izimobil/django-rest-framework-datatables#115]
I notice that the travis build has [not run for a few months](https://travis-ci.org/github/izimobil/django-rest-framework-datatables).  Travis apparently was acquired and customers are having to [undertake extra steps to get builds running on travis.com](https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works).

I recently ported another project to github actions, so happy to do this here if required.

**Comment by izimobil** [comment]
Indeed, I've updated the config, it seems OK now, thanks.
