### ISSUE TITLE
Export all the results to the CSV

### ISSUE THREAD

**Issue by afsangujarati93** [izimobil/django-rest-framework-datatables#125]
Currently, when the CSV is exported, it only exports the visible results to the CSV file. I don't see a way to export all the (filtered) results to the CSV. How can this be achieved with django rest framework datatables?

**Comment by izimobil** [comment]
Hi,

If you use the CSV export plugin from DataTables, its normal that it exports only the data that is loaded on the client side.
If you want to export all data, you will have to add a button to the table that link to a server URL that returns a CSV response, you can try `django-import-export` which is a good package for this.

Anyway, this is not related to DRF-datatables, I'm closing the issue.
