### ISSUE TITLE
Issue retrieving fields with a 'source' attribute

### ISSUE THREAD

**Issue by darkpixel** [izimobil/django-rest-framework-datatables#127]
Give a model:
```
class Person(models.Model):
    first_name = models.CharField(max_length=255)
    surname = models.CharField(max_length=255)
```

And a serializer:
```
class PersonSerializer(...):
    last_name = serializers.CharField(max_length=255, source='surname')

    class Meta:
      model = Person
      fields = ['first_name', 'last_name']
```

And a table with:
```
<TH data-data="first_name"></TH>
<TH data-data="last_name"></TH>
```

The system fails to find the 'last_name' field and causes Django to throw a 500 error:

```django.core.exceptions.FieldError: Cannot resolve keyword 'last_name' into field. Choices are: </snip>```

Referencing the field as ```data-data="surname"``` doesn't cause the 500 error, but you also don't get any data in that field due to it not being returned by the serializer.

**Comment by izimobil** [comment]
Hi,

I don't understand your use case, why not returning `surname` property directly in `PersonSerializer` ?
Moreover, does the 500 error appear when calling your endpoint without the `?format=datatables` query parameter ?
If so, this is not related to DRF-Datatables.

**Comment by darkpixel** [comment]
I was able to pull the data without ```?format=datatables```, but when adding it back, DataTables appeared to be failing over a renamed field.

For the life of me, I can't seem to duplicate it anymore.  I must have had something messed up elsewhere without realizing it.
