### ISSUE TITLE
Problem with raw queryset

### ISSUE THREAD

**Issue by doolieSoft** [izimobil/django-rest-framework-datatables#148]
Hello,

When I use a raw queryset, I get this exception :
![image](https://github.com/izimobil/django-rest-framework-datatables/assets/6433793/013f8693-3742-4587-a0f1-57f5fd64c9c5)

I have found a solution by replacing queryset.count() by len(queryset) and made a new pull request.

Thanks,
Stefano

**Comment by izimobil** [comment]
Fixed by https://github.com/izimobil/django-rest-framework-datatables/commit/07af6cd8a519fe2d8c7a0b2cdc6700a07ad20cc2
