### ISSUE TITLE
Publish new version in pypi

### ISSUE THREAD

**Issue by bryan-brancotte** [izimobil/django-rest-framework-datatables#16]
Hi
I really like this package, could you please publish a new build on pypi ? I need both https://github.com/izimobil/django-rest-framework-datatables/pull/11/commits/99e6f2161495e306e14c5615eea63e83ff18d981 and https://github.com/izimobil/django-rest-framework-datatables/commit/4eb270446b7fa133acc061d024cbe9d7729199ae.
Thanks,

**Comment by izimobil** [comment]
Done, version 0.4.0 is on pypi now.
