### ISSUE TITLE
Export button (all datas)

### ISSUE THREAD

**Issue by ptiyoda** [izimobil/django-rest-framework-datatables#20]
Hello thanks for your amazing job,

I try to add export button to export all data of table, but it's not working.
If i refer to https://datatables.net/reference/type/selector-modifier#Server-side-processing, with serverside mode we need to create this feature to export all table.
What is the best way with your python module?

:)

**Comment by izimobil** [comment]
Sorry this is not a DRFDT issue, you'll have to implement your own "export" view and link it to the export button.
