### ISSUE TITLE
compatibility with raw_query and count error

### ISSUE THREAD

**Issue by mgobi** [izimobil/django-rest-framework-datatables#22]
Hi, great solution it works very good. However when i want to use more complex queries using Rawquery i will get a count error when visiting http://127.0.0.1:8000/api/news/?format=datatables:

Exception Type: AttributeError at /api/news/
Exception Value: 'RawQuerySet' object has no attribute 'count'

is there a solution to this?

thanks for your response,
best regards,
MG

**Comment by izimobil** [comment]
Sorry django-rest-framework-datatables does not support raw querysets. I could deal with the count() issue but it will fail at filtering anyway.
What you could do is write your own filters.py and pagination.py based on django-rest-framework-datatables ones.
Regards
