### ISSUE TITLE
support for yadcf?

### ISSUE THREAD

**Issue by will-emmerson** [izimobil/django-rest-framework-datatables#26]
There is something called yadcf (https://github.com/vedmack/yadcf) which makes it easy to add filters to datatables. For it to work properly when serverside=true, the server has to output some extra data.
I initially thought this is something that could be added to django-rest-framework-datatables but it's probably too specific and can't be made generic.
So just wondering if it's possible to modify what django-rest-framework-datatables outputs and where the best place would be to do it?

The extra data I need to output is all the possible values for a certain column *before* filtering, so that a select can be shown on the front end.

**Comment by izimobil** [comment]
Hi, if I understand correctly, you need to fetch data to build the filters selects of your Datatable ?
If so, why don't you just make a special request to fetch your filters data **before** building you datatable ?
Something like:
```

$.get('/api/filter-data/', function(res.data) {
    // build filter selects and datatable...
});
```

**Comment by tricid** [comment]
One huge improvement to this that I haven't been able to figure out yet, also why it ended up being put in the render:  If I could find the place after filtering but before pagination I can make it only show relevant filters.  With each filter chosen on a column, other columns likely lose potential options.  The way I did it will show all options for all columns at all times even if they'd return an empty set. 

It needs to happen before pagination though or you'd only get the options for whats visible on your current page.  This is basically the default behavior as is using yadcf with this lib. 

Any hints on a better place to achieve this?  I started to do it in filters.py but it wasn't immediately obvious how I can add to the data object like I'd need.  I only see querysets in there.

**Comment by izimobil** [comment]
While not merged yet, pull request https://github.com/izimobil/django-rest-framework-datatables/pull/32 should do what you are requesting, it adds an "options" dict to the JSON response.

**Comment by TauPan** [comment]
Looking at this and #32 I wasn't sure how to pass the data from DRF to yadcf and came up with a very different approach:

I just call OPTIONS on the data url and get the field options directly from DRF.

Example:
```js
export async function finding_table(selector, url) {
  var options;
  const dt = $(selector).DataTable(new FindingDataTableOptions(url));
  await $.ajax(url, {method: 'OPTIONS', dataType: 'json'}).done((x) => options = x);
  yadcf.init(dt, [
    {column_number: 0,
     filter_type: 'text',
     filter_default_label: 'Filter Vuln IDs',
     regex_check_box: true
    },
    {column_number: 1,
     filter_type: 'text',
     filter_default_label: 'Filter Title',
     exclude: true,
     regex_check_box: true
    },
    {column_number: 3,
     filter_type: 'range_number_slider'
    },
    {column_number: 5,
     filter_type: 'range_number_slider'
    },
    {column_number: 7,
     filter_type: 'range_number_slider'
    },
    {column_number: 8,
     filter_type: 'multi_select',
     filter_default_label: 'Select CWEs',
     data: options.data.actions.POST.cwe_id.choices.map(x => `<option>${x.display_name}</option>`),
     data_as_is: true,
     select_type: 'chosen'
    }
  ]);
  return dt;
}
```

CWE ids in that case is a ChoiceField in DRF with choices set to the options present in the database. This is basically as proposed in https://github.com/izimobil/django-rest-framework-datatables/issues/26#issuecomment-439394712 but without an *extra* api call, since DRF already supports OPTIONS.
