### ISSUE TITLE
New release with official Django 2.1 and DRF 3.9 support. 

### ISSUE THREAD

**Issue by felixxm** [izimobil/django-rest-framework-datatables#27]
@izimobil Thanks for creating this package :rocket:

Can we create a new release with official support of Django 2.1 and DRF 3.9? I created a simple PR #25 for that. Thanks in advance. Please let me know if I can help you in any other way.

**Comment by felixxm** [comment]
@izimobil  Any update on this? If you need any help just let me know :+1: . I will be really grateful for a new version with official support for Django 2.1 and DRF 3.9 :bowing_man:

**Comment by izimobil** [comment]
Here you go: https://pypi.org/project/djangorestframework-datatables/ :)

**Comment by felixxm** [comment]
@izimobil Many thanks :rocket:
