### ISSUE TITLE
Oracle, subquery and outeref and counting

### ISSUE THREAD

**Issue by danizen** [izimobil/django-rest-framework-datatables#28]
Oracle will not do a counting query with subqueries in it, but the WHERE (SELECT ... ) IS NOT NULL is OK.
The solution is to count only on the primary key

```python
count = queryset.values(queryset.model._meta.pk.name).count()
```

This is also an issue with DRF, and maybe with Django itself.

https://github.com/izimobil/django-rest-framework-datatables/blob/71f6a4ceab3783910ec9bb02b6532ff7e77c5178/rest_framework_datatables/pagination.py#L29

**Comment by izimobil** [comment]
If like you said its "an issue with DRF, and maybe with Django itself", there's little I can do at this package level, you should report it to Django bugtracker.
