### ISSUE TITLE
DRF Token Aunthentication Support

### ISSUE THREAD

**Issue by computerquest** [izimobil/django-rest-framework-datatables#29]
I have followed the tutorial and have found nothing on how to integrate this library with DRF token authentication (my API must use that). When I make the requests to the url DRF blocks the request because it has no validation token. All I would need to do is attach a header to the request. Is there a way to do this?

**Comment by felixxm** [comment]
@computerquest You can set authorization header before sending request, e.g.

```javascript
DataTable({
    ...
    ajax: {
        processing: true,
        url: `https://...`,
        beforeSend: set_authorization_header,
    },
    ...
});
```
where `set_authorization_header()` will just set authorization  header, e.g.:
```javascript
function set_authorization_header(request){
    ...
    request.setRequestHeader('Authorization', 'Bearer ' + access_token);
};
```

**Comment by izimobil** [comment]
Hi,
@felixxm is right, this is how to do it, regardless of django-rest-framework-datatables.
