### ISSUE TITLE
multi_filter columns logical connection

### ISSUE THREAD

**Issue by ChrFr** [izimobil/django-rest-framework-datatables#3]
First of all, thanks for the great work on implementing this plugin, it saved me a lot of time :)

I have a small issue that i try to explain with the multi_filter example of the official DataTables site (https://datatables.net/examples/api/multi_filter.html)

in this example: when you filter the name column by "Angelica" you get **one** row:
![image](https://user-images.githubusercontent.com/1932619/39579564-6235181c-4ee7-11e8-890e-7cfb3a60e8a6.png)

when you filter the name column by "Accountant" you get **two** rows:
![image](https://user-images.githubusercontent.com/1932619/39579625-7f422648-4ee7-11e8-8faf-4a10ed6bdd8b.png)

combining both you get zero rows (because the one Angelica is no accountant):
![image](https://user-images.githubusercontent.com/1932619/39579691-a98f5d76-4ee7-11e8-9a63-e72222b65bbc.png)

So clearly the column filters are linked logically with **AND**

Your plugin does it differently server-side. The single column filters work fine. But if you combine them you would get **three** rows: the two accountants and Angelica.

The reason: In line 43 and 45 the _filters.py_ the individual column filters are linked with **OR**
![image](https://user-images.githubusercontent.com/1932619/39580080-9123de50-4ee8-11e8-84d4-90d5f810dd29.png)

I guess there should be **AND** operations instead to match the way DataTables is filtering multiple columns client-side.
Locally i replaced the two occurences with _&=_ on my computer and it works as expected.

Thanks for reading, 
best regards Christoph

**Comment by izimobil** [comment]
Hi,
I didn't know column search was filtered with AND operator, would you like to submit a pull request with tests please ?
Thanks !

**Comment by izimobil** [comment]
Nevermind, it's a simple fix, I'll do it myself, thanks for the report.

**Comment by izimobil** [comment]
Fixed: https://github.com/izimobil/django-rest-framework-datatables/commit/5560ddbc711808f7d242b0ec88e042c99212ed21

**Comment by ChrFr** [comment]
Sorry, i did not read this in time. Thank you for fixing!
