### ISSUE TITLE
CRUD Operations

### ISSUE THREAD

**Issue by msteinbeck** [izimobil/django-rest-framework-datatables#35]
Hi, thank you for this very useful datatable component. Does this component also support CRUD operations (using the REST API)?

**Comment by izimobil** [comment]
No, this is not supported, maybe one day there will be support for the Datatables Editor plugin but for now I'm way too busy to work on it.

**Comment by bahaspieler** [comment]
you can still do the CRUD operations here. Create a view for the update or delete operation. Then modify your `$('#yourtable').DataTable()` `"columns":`  section like below to render a button for every rows.
```
"columns": [
                    {"data": "####"},
                    .
                    .
                    .
                    {"data": "id", "name": "id",
                        fnCreatedCell: function (nTd, sData, oData, iRow, iCol) {
                            $(nTd).html("<a href='/your_defined_url_in_urls.py/"+oData.id+"' class='btn btn- 
                            primary' style='Can give some styles'>Edit</a>");
                    }},
                ]
```
