### ISSUE TITLE
Ordering on a column with many duplicates 

### ISSUE THREAD

**Issue by parander** [izimobil/django-rest-framework-datatables#42]
If you sort on a column that contains many duplicates (more duplicates than the page size) you might end up iterating through the same rows in the datatable (and completely skip some) as you click through the pages.

I'm not sure what the correct terminology is for this is but it  happens because of how order by together with limit & offset works in the database. The easiest way to reproduce this behavior is to set the datatables page size to 1 and then sort by a column where you know there's a lot of duplicates. As you paginate through the table you will notice that some rows show up on multiple pages.

The solution for this is to add a secondary column to sort by (preferably one that contains unique rows such as an id column), that way we will get a strict order of the rows that contains ties.

Pull  request #41  or a proposed solution where I'm adding an attribute on the API view itself and then have the filter test for the existence of such attribute before ordering the queryset. 

Update: I tried to reproduce the issue with the fixture in test_data.json together with sqlite3 but was unable to trigger the bug. However after changing to a mysql backend I'm able to reproduce the issue by setting the datatable page size to 1 and sort by album year ascending:

...
Page 3: 4 | Bob Dylan | Highway 61 Revisited | 1965
Page 4: 3 | The Beatles | Revolver | 1966 | Pop Rock, Psychedelic Rock
Page 5: 9 | Bob Dylan | Blonde on Blonde | 1966
Page 6: 9 | Bob Dylan | Blonde on Blonde | 1966
Page 7: 1 | The Beatles | Sgt. Pepper's Lonely Hearts Club Band | 1967
...

So the same row is returned for page 5 & 6 and the album:
"2 | The Beach Boys | Pet Sounds | 1966" is never retrieved.

**Comment by izimobil** [comment]
Fixed with #48, thanks.
