### ISSUE TITLE
Pagination not working

### ISSUE THREAD

**Issue by sunilkothiyal** [izimobil/django-rest-framework-datatables#45]
I am working with 1 million MySQL records. I am just showing the data from the database to the HTML template. But **it's taking more than 1 minute to process a single page** rendering.

I don't know why pagination is not working of the library?

Can anyone help me to display that large amount of data?

**Comment by izimobil** [comment]
Please provide more context or sample code, I can't help otherwise...

**Comment by 1sunny** [comment]
Here is my code- 

**html.template-**
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0/css/bootstrap.css">
  <link rel="stylesheet" href="//cdn.datatables.net/1.10.16/css/dataTables.bootstrap4.min.css">
        <table id="albums" class="table table-striped table-bordered" style="width:100%">
          <thead>
            <tr>
              <th>Name/th>
              <th>Email</th>
              <th>Phone</th>
              <th>Campany  Name</th>
              </tr>
          </thead>
        </table>

  <script src="//code.jquery.com/jquery-1.12.4.js"></script>
  <script src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
  <script src="//cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>
<script>
      $(document).ready(function() {
          var table = $('#comapny').DataTable({
              "serverSide": true,
              "processing": true,
              "paging": true,
              "ajax": "/sf/api/company/?format=datatables",
              "columns": [
                  {"data": "Name",},
                  {"data": "Email",},
                  {"data": "Phone"},
                  {"data": "Company_name"},
              ]
          });
      });
  </script>
**view.py-**
class CompanyViewSet( viewsets.ModelViewSet):
    queryset = Company.objects.all()
    serializer_class = CompanySerializer
    pagination_class  = DatatablesPageNumberPagination

**serializer.py**
class ArtistSerializer(serializers.ModelSerializer):
    
    class Meta:
        model = Company
        fields = ('id', 'Name', 'Email', 'Phone' , 'Company_name' )
        datatables_always_serialize = ('id',)

1- Operating system- Windows 7
2- Database- MYSQL
3- Total records in company-table- 1,000000+
4- datatable taking time to render- 1 minute ~1.30 minute

**Comment by izimobil** [comment]
No idea... drf-datatables does not evaluate the whole queryset, so I suspect your queryset must be evalued somewhere in your code, try to install django-debug-toolbar and inspect the SQL requests.

**Comment by CarlosBorroto** [comment]
I'm also having issues with pagination. I just started playing the `django-rest-framework-datatables` and I'm guessing I'm doing something wrong.

These are my `rest-framework` settings:
```
REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': (
        'rest_framework.filters.SearchFilter',
        'rest_framework_datatables.filters.DatatablesFilterBackend',
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework_datatables.pagination.DatatablesPageNumberPagination',
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
        'rest_framework_datatables.renderers.DatatablesRenderer',
    ),
    'PAGE_SIZE': 50
}
```

This is what I get from the `JSONRenderer`:
```
{
"count": 516,
"next": "<END_POINT_URL>/?format=json&page=2",
"previous": null,
"results": [...] // 50 items
```

And this is what I get from the `DatatablesRenderer`:
```
{
"data": [...], // 516 items
"recordsFiltered": 516,
"recordsTotal": 516,
"draw": 1
}
```

For some reason, the `DatatablesRenderer` is not doing pagination at all.

Thanks!

**Comment by CarlosBorroto** [comment]
Deleted comment.

Oops, I'm also new to datatables. Looking at the code and the actual requests the API is getting, I can see datatables uses `length` query parameter to request the appropriate number of records. Everything is working in my setup.
