### ISSUE TITLE
Length = -1 queries default PAGE_SIZE in settings instead of queryset returned from viewset

### ISSUE THREAD

**Issue by robinsandstrom** [izimobil/django-rest-framework-datatables#49]
I noticed that when trying to query all records, django-rest-frame-work-datatables returns the default PAGE_SIZE in settings instead of the queryset returned by the viewset.

**Comment by robinsandstrom** [comment]
Monkey-patched it

class MyViewSet(viewsets.ModelViewSet):

    serializer_class = MySerializer

    def get_queryset(self):
        length = self.request.GET.get('length')
        if length == '-1':
            self.pagination_class = None
        queryset = MyObject.objects.all()
        return queryset

**Comment by ArkFreestyle** [comment]
Thanks, your monkey patch is awesome!

**Comment by maxprehl** [comment]
This was actually patched in PR #46, merged on June 18, 2019.

However there has been no subsequent release of the updated code.  The current available release is version 0.5.0 from Mar 31, 2019.
