### ISSUE TITLE
Dealing with nested relationships

### ISSUE THREAD

**Issue by neighlyd** [izimobil/django-rest-framework-datatables#5]
Hello,

I apologize if this isn't the right place to ask this question, but I am having a rough time trying to get this package working with nested relationships. I have tried using [DRFs built in solution](http://www.django-rest-framework.org/api-guide/relations/#nested-relationships), [DRF-Flex-Fields](https://github.com/rsinger86/drf-flex-fields), and [Dynamic Rest](https://github.com/AltSchool/dynamic-rest). None of these options seem to be able to expand my sub-serializers and apply the DRF-Datatables formatting appropriately.

Instead, what is happening is that the nested relationships are being stripped away and only the first layer is being presented within the `data:[...]` layer that is fed to the datatable.

**Comment by izimobil** [comment]
Hello,
Sorry I can't help here, AFAIK Datatables expects a data array and does not know how to deal with nested structures.
At best it can do [this](https://datatables.net/examples/ajax/deep) but this is not currently supported by drf-datatables.

**Comment by neighlyd** [comment]
Hi,

The nested objects were the type of nested structures I was talking about. My API is nested in that fashion.

It seems that drf-datatables strips out nested layers during the `_filter_unused_fields()` method. I'm going to hack around with it to see if I can get it to filter unused fields while still maintaining the information from columns that have nested data.

**Comment by izimobil** [comment]
Fixed by https://github.com/izimobil/django-rest-framework-datatables/pull/7
