### ISSUE TITLE
Multiple search filter not working 

### ISSUE THREAD

**Issue by mafiagamer** [izimobil/django-rest-framework-datatables#51]
Hi Expert,

When I try to search with multiple columns I am getting the 500 error. Please help me to fix it.

JS CODE:
`"use strict";

 var KTDatatablesSearchOptionsAdvancedSearch = function() {

	$.fn.dataTable.Api.register('column().title()', function() {
		return $(this.header()).text().trim();
	});

	var initTable1 = function() {
		// begin first table
		var table = $('#kt_table_1').DataTable({
			responsive: true,
			colReorder: true,
			// rowGroup: {dataSrc: 'SID'},

			// Pagination settings
			dom: `<'row'<'col-sm-12'tr>>
			<'row'<'col-sm-12 col-md-5'i><'col-sm-12 col-md-7 dataTables_pager'lp>>`,
			// read more: https://datatables.net/examples/basic_init/dom.html

			lengthMenu: [5, 10, 20, 30, 50],

			pageLength: 20,

			language: {
				'lengthMenu': 'Display _MENU_',
			},

			searchDelay: 500,
			processing: true,
			serverSide: true,
			ajax: {
				url: '/patch/api/dt/?format=datatables',
				type: 'GET',
				data: {
					// parameters for custom backend script demo
					columnsDef: ['SID', 'DBSID','DC',"HOST","os_version","MEMORY",'TYP','ZHCODE','EUDP','SYSTEMROLE'],
				},
			},
			columns: [
									{'data': 'SID', 'name': 'SID', 'autoWidth':true},
									{'data': 'DBSID', 'name': 'DBSID', 'autoWidth':true},
									{'data': 'ZHCODE', 'name': 'ZHCODE', 'autoWidth':true},
									{'data': 'DC', 'name': 'DC', 'autoWidth':true},
									{'data': 'TYP', 'name': 'TYP', 'autoWidth':true},
									{'data': 'HOST', 'name': 'HOST', 'autoWidth':true},
									{'data': 'os_version', 'name': 'os_version', 'autoWidth':true},
									{'data': 'MEMORY', 'name': 'MEMORY', 'autoWidth':true},
									{'data': 'EUDP', 'name': 'EUDP', 'autoWidth':true},
									{'data': 'SYSTEMROLE', 'name': 'SYSTEMROLE', 'autoWidth':true}
								],

			columnDefs: [
				{
					targets:'_all',
				className: 'dt-center',
			},

				{
					targets: 2,
					className: 'dt-center',
					render: function(data, type, full, meta) {
						var status = {
							'ZH006': {'title': 'ZH006', 'state': 'warning'},
							'ZH001': {'title': 'ZH001', 'state': 'warning'},
							'ZH029': {'title': 'ZH029', 'state': 'accent'},
							'ZH019': {'title': 'ZH019', 'state': 'accent'},
							'ZH037': {'title': 'ZH037', 'state': 'focus'},
							'ZH002': {'title': 'ZH002', 'state': 'danger'},
							'ZH005': {'title': 'ZH005', 'state': 'info'},
						};
						if (typeof status[data] === 'undefined') {
							return data;
						}
						return '<span class="kt-badge--' + status[data].state + '"></span>&nbsp;' +
							'<span class="kt-font-bold kt-font-' + status[data].state + '">' + status[data].title + '</span>';
					},
				},
				{
					targets: -2,
					className: 'dt-center',
					render: function(data, type, full, meta) {
						var status = {
							false: {'title': 'PROD', 'class': '<a href="#" class="btn btn-sm btn-clean btn-icon btn-icon-md" title="NON-EUDP"><i class="fa fa-times-circle k-font-success"></i></a>'},
							true: {'title': 'VLAB', 'class': ' <a href="#" class="btn btn-sm btn-clean btn-icon btn-icon-md" title="EUDP"><i class="fa fa-check-circle"></i></a>'},
						};
						if (typeof status[data] === 'undefined') {
							return data;
						}
						return status[data].class;
					},
				},
			],
		});

		var filter = function() {
			var val = $.fn.dataTable.util.escapeRegex($(this).val());
			table.column($(this).data('col-index')).search(val ? val : '', false, false).draw();
		};

		var asdasd = function(value, index) {
			var val = $.fn.dataTable.util.escapeRegex(value);
			table.column(index).search(val ? val : '', false, true);
		};

		$('#m_search').on('click', function(e) {
			e.preventDefault();
			var params = {};
			$('.kt-input').each(function() {
				var i = $(this).data('col-index');
				if (params[i]) {
					params[i] += '|' + $(this).val();
				}
				else {
					params[i] = $(this).val();
				}
			});
			$.each(params, function(i, val) {
				// apply search params to datatable
				table.column(i).search(val ? val : '', true);
			});
			table.table().draw();
		});

		$('#m_reset').on('click', function(e) {
			e.preventDefault();
			$('.kt-input').each(function() {
				$(this).val('');
				table.column($(this).data('col-index')).search('', false, false);
			});
			table.table().draw();
		});

		$('#m_datepicker').datepicker({
			todayHighlight: true,
			templates: {
				leftArrow: '<i class="la la-angle-left"></i>',
				rightArrow: '<i class="la la-angle-right"></i>',
			},
		});

	};

	return {

		//main function to initiate the module
		init: function() {
			initTable1();
		}
	};

}();

jQuery(document).ready(function() {
	KTDatatablesSearchOptionsAdvancedSearch.init();
});
`

Server-side : 
`
class Prodclddata(viewsets.ModelViewSet):

    try:
        queryset = COMPUTED_HOST_DETAILS.objects.filter(IS_VLAB=False)
        serializer_class = SystemSerializer
    except Exception as e:
        raise
`
**Search:**
![image](https://user-images.githubusercontent.com/23234118/62269233-04a7cd00-b450-11e9-81ce-26587ba7f747.png)

**ERROR**
![image](https://user-images.githubusercontent.com/23234118/62269287-2dc85d80-b450-11e9-9b32-19a8fc4f66f4.png)

**Comment by izimobil** [comment]
It's will be hard to help you without a traceback of your 500 error...

**Comment by izimobil** [comment]
No feedback.
