### ISSUE TITLE
Filtering large dataset is slow

### ISSUE THREAD

**Issue by Rubyj** [izimobil/django-rest-framework-datatables#53]
@izimobil 

Filtering a table that links back to a large Model dataset is relatively slow. My use case is that the dataset is over a million records and there are about 7 columns the filtering is checking against. 

Do you have any recommendations on how to speed this up from the drfd side? Overwriting the filter backend? Specifying which column to filter by?

**Comment by Rubyj** [comment]
@izimobil Update: I sped things up by filtering on select columsn only and by adding trigram indexes on certain columns.

That said, I am unable to index date columns in that way on postgres and this framework generates a LIKE UPPER(%date%::text) even for date fields which you can not make an index for. Any idea what I could do for a date field?

**Comment by chainwang31** [comment]
I have the same question. It takes me about 10 sec to display data (50 rows, out of 3.5 million rows in total) on the first page, most of the time spent on the XHR to the api fetching data, of which the size is only 17.4kb shown by network). Searching takes about 40 sec, with 1 draw on the table.

Any way to speed this up? (can anything be done to the queryset?)

**Comment by izimobil** [comment]
Hi,

DRF Datatables does not do any fancy stuff when filtering the queryset, just basic django lookups.
As @Rubyj noted, maybe reducing the number of searchable columns will help.

@Rubyj, @chainwang31 : You should both profile times with django only and with django-rest-framework-datatables. If there's a big difference between the two, then maybe there's an issue to solve in this package.
Keep in mind DRF-datatables provides only basic filtering, if you want something more powerful you will probably have better results by implementing your own optimized filter backend.
