### ISSUE TITLE
Support Django 3

### ISSUE THREAD

**Issue by mirodrigom** [izimobil/django-rest-framework-datatables#56]
Are you thinking to upgrade to django 3? Will be release in december 2019.
Im using django (dev3), and get this error (because "six" library will not be used in django 3).
This error shows only when tried to use pagination. rest of code as far i know works like a charm.

`ImportError: Could not import 'rest_framework_datatables.pagination.DatatablesPageNumberPagination' for API setting 'DEFAULT_PAGINATION_CLASS'. ImportError: cannot import name 'six' from 'django.utils' (/home/xxx/django/django/utils/__init__.py).
`

Thank you.

**Comment by samatix** [comment]
I have created a PR https://github.com/izimobil/django-rest-framework-datatables/pull/62 to correct the issue. 

Waiting on the maintainers to confirm. 

Thanks
Ayoub

**Comment by Kompas** [comment]
Any news on this? At this moment the package does not work with the latest Django 3.

**Comment by samatix** [comment]
Hi @Kompas , there was a compatibility issue between the versions used for DRF and Django versions. Now it should be good and it's pending @CarlosBorroto to review.

**Comment by izimobil** [comment]
Version 0.5.1 now support Django 3.0
