### ISSUE TITLE
search disabled with filter backend

### ISSUE THREAD

**Issue by marouenbg** [izimobil/django-rest-framework-datatables#57]
Hi @izimobil ,

drf-datatables search field works fine.
When I add in my class a DjangoFilterBackend to filter by id, the search bar stops working.
Here is my class in my `api_views.py`

```
class ExResultListUp(ListAPIView):
        queryset = ExResultUp.objects.all().order_by('overlap')
        serializer_class = ExResultSerializerUp
        filter_backends = (DjangoFilterBackend,)
        filter_fields = ('id',)
```
When I comment this line `filter_backends = (DjangoFilterBackend,)`, the search bar in datatables works fine.

**Comment by viseshrp** [comment]
This is because, by defining filter_backends again in your APIView, you are effectively overriding the Datatables Filter backend that you specified in settings.py, which is vital for the search function to work. Add it back here like,
```
filter_backends = [DjangoFilterBackend, DatatablesFilterBackend]
```
This should fix it.

**Comment by marouenbg** [comment]
Kudos @viseshrp
