### ISSUE TITLE
Serverside filtering not working, when model has Foreign key

### ISSUE THREAD

**Issue by Roccoriu** [izimobil/django-rest-framework-datatables#58]
I have a fairly complex set of models, that use Foreign keys. Unfortunately filtering does not seem to work when a Field contains a Foreign key. If you try to filter the server responds with a 500 internal server error. 
The actual error message is the following: Related Field got invalid lookup: icontains.

I know this happens, because django-rest-framework-datatables tries to use icontains on a foreign key, which is not possible. 

I now wonder if something can be done, or if there is at least something I can do to fix this issue?

**Comment by se0siris** [comment]
Filtering on foriegn keys works - you need to add your relation on the table using the name attribute so that it can be built into the request URL:

https://django-rest-framework-datatables.readthedocs.io/en/latest/tutorial.html#a-more-complex-and-detailed-example
