### ISSUE TITLE
Problems displaying and filtering Method and ReadOnly Fields 

### ISSUE THREAD

**Issue by neighlyd** [izimobil/django-rest-framework-datatables#6]
It appears that the filter logic doesn't have a way to deal with calculated fields (i.e. `SerializerMethodField()` or `ReadOnlyField()`).

Currently, if you attempt to include one of these fields as a column, it will run the field through `filter_queryset()` in `filters.py`. Unfortunately, since they are not fields on the model, it returns the following error:

`FieldError... Cannot resolve keyword`.

This happens even when setting the column to `'searchable': false`.

If I set the `name:` field in `columns` to a different field in the model, it will display the data. However, it is not searchable or filterable. Doing so returns the following error:

`Related Field got invalid lookup: icontains`

It seems that the way forward would be to provide a separate query param that stipulates what the filter field should be for a given column. However, I don't think that Datatables has this functionality built in with how it formats url query params for server side processing.

Perhaps it would be possible to repurpose the `columns[i][name]` param for this purpose, but that seems hacky-af.

**Comment by izimobil** [comment]
Hi, thanks for the feedback. Yes this would be interesting I think, If you can submit a pull request with tests and documentation I'll be happy to review it and merge it.

**Comment by izimobil** [comment]
Closing this since PR was merged. See: https://github.com/izimobil/django-rest-framework-datatables/pull/7

**Comment by morenoh149** [comment]
Here's an example that might help others

models.py
```
class Person(models.Model):
    first_name = models.CharField(blank=True, max_length=300)
    middle_name = models.CharField(blank=True, max_length=300)
    last_name = models.CharField(blank=True, max_length=300)
```
serializers.py
```
class PersonSerializer(serializers.ModelSerializer):
    id = serializers.IntegerField(read_only=True)
    name = serializers.SerializerMethodField()

    class Meta:
        model = Person
        fields = (
            "id",
            "name",
        )

    def get_name(self, obj):
        if obj.middle_name:
            return f"{obj.first_name} {obj.middle_name} {obj.last_name}"
        else:
            return f"{obj.first_name} {obj.last_name}"
```
app.js
```
$("#table").DataTable({
  serverSide: true,
  ajax: "/api/persons/?format=datatables",
  ordering: false,
  pagingType: "full_numbers",
  columns: [
    {
      data: "name",
      name: "first_name, middle_name, last_name",
      orderable: false,
      searchable: true,
      render: function(name, type, row, meta) {
        return name;
      }
    },
  ]
});
```
views.py
```
class PersonViewSet(viewsets.ModelViewSet):
    queryset = Person.objects.all().order_by("id")
    serializer_class = PersonSerializer
```
index.html
```
      <div class="table-responsive">
        <table class="table table-hover table-sm w-100" id="table">
          <thead>
            <tr>
              <th>Name</th>
            </tr>
          </thead>
        </table>
      </div>
```
