### ISSUE TITLE
Include `tests` in published package?

### ISSUE THREAD

**Issue by crazyscientist** [izimobil/django-rest-framework-datatables#63]
Hi there,

I'm trying to build an RPM package on https://build.opensuse.org for your Python package. And it would be really cool, if the Python package included the `tests`.

Would you mind adding them in the next release?

**Comment by izimobil** [comment]
I'm not using OpenSuse and not sure how to do this right, also including tests in releases seems pretty uncommon in python packaging world.

What I can do is publish a source release each time a new version is released so you can include tests in the opensuse package.

**Comment by izimobil** [comment]
In fact, source packages are already published, so I suggest you use them to prepare your opensuse package with tests included. Thanks !
