### ISSUE TITLE
Is it possible to send data via POST?

### ISSUE THREAD

**Issue by clog-rocks** [izimobil/django-rest-framework-datatables#69]
Hi there,

thanks for that great app, it works perfect. Unfortunately DataTables.js, when sending request to DRF API endpoint puts a lot of parameters to URL. That really clogs up logs. There is simple solution, to this problem: send parameters via POST request, described here: https://stackoverflow.com/questions/33862482.

Is it possible to achieve that with DRFD, make it work with POST as well as GET?

Thanks!

**Comment by morenoh149** [comment]
did you try adding that key value to https://github.com/izimobil/django-rest-framework-datatables/blob/master/example/albums/templates/albums/albums.html#L65 ?

**Comment by clog-rocks** [comment]
I just did, the same result as in my app.

Console says `Failed to load resource: the server responded with a status of 400 (Bad Request)` and pop up with `DataTables warning: table id=albums - Ajax error. For more information about this error, please see http://datatables.net/tn/7` gets displayed.
Log is `"POST /api/albums/?format=datatables HTTP/1.1" 400 15407`.

**Comment by izimobil** [comment]
At the moment this is not possible, but it could be easily done by replacing `request.query_params` with `request.POST` in DRF-datatables code, a good test would be something like:

```
if request.POST.get('draw') is not None:
    params = request.POST
else:
    params = request.query_params
```

If you manage to make it work, feel free to open a PR with tests included.

Thanks.

**Comment by clog-rocks** [comment]
Thanks for that.  I tried to make it work but didn't manage. I am getting 403 on my API endpoint after making that change in `filters.py`:

```
          # parse query params
          # getter = request.query_params.get
          if request.POST.get("draw") is not None:
              getter = request.POST.get
          else:
              getter = request.query_params.get
```

I am not sure if problem is that code or my ModelViewSet endpoint.

**Comment by CristopherH95** [comment]
Is there any update regarding the possibility of integrating pull request #70, which seems to be related to this? I had planned to use this package, but the environment I'm working in has limits on query strings, which makes using GET requests only a blocker.

**Comment by izimobil** [comment]
Fixed !
