### ISSUE TITLE
Planned timeline for python 2 support?

### ISSUE THREAD

**Issue by TauPan** [izimobil/django-rest-framework-datatables#71]
I'd like to know how you (@izimobil ) feel about Python 2 support, since I'm trying to develop optional support for django-filters and I'm having real trouble carrying Python 2 along.

It's no problem raising a SkipTest exception if the django-filters module is not present in python 3, but in Python 2 this will cause an error and this would make the tests for the new functionality quite complicated.

**Comment by izimobil** [comment]
Hi @TauPan, I'm not sure if we should drop python 2... Maybe, what's really blocking ?

**Comment by TauPan** [comment]
This is really about #72 

To make django-filter support truly optional, I'm currently skipping all the django-filter tests if django-filter is not available. This is easy to do with Python 3 but very hard and ugly in Python 2. See https://stackoverflow.com/questions/12487532/how-do-i-skip-a-whole-python-unittest-module-at-run-time for possible solutions.

Maybe you have a better idea how to accomplish this.

I did not make any python 2 incompatible changes to the main code (i.e. without django-filters), which means that the python 2 based tests still work, but I get two errors when SkipTest is raised.

The other problem I have is that django-filters changed their api in >= 2.2.0 *and* they dropped python 2 support at the same time. Maybe my changes are compatible with an older version of django-filter that still supports python 2. I'd have to give it a try.

Do you happen to know if there are active projects using django-rest-framework-datatables that are still python 2 based?

**Comment by izimobil** [comment]
I have merged #72 manually, so we will drop python 2 support on 0.6.0 release.
