### ISSUE TITLE
URL too long

### ISSUE THREAD

**Issue by Engensmax** [izimobil/django-rest-framework-datatables#73]
Heya, first off thanks a lot for this module as it is super simple to implement and very effective.

I am having this issue where the ajax-url becomes longer than 2000characters and therefore stops functioning and I assume I am doing something wrong. 

This is the url i get:
`/models/result_overview/?format=datatables&Lot=&MatNo=&Product=&Comment=&Tester=&Result__testDate_min=&Result__testDate_max=&TestEquipment=7500%2F5%3A%20Zwick&TestInstruction=&Result__Tag__name=&draw=9&columns%5B0%5D%5Bdata%5D=id&columns%5B0%5D%5Bname%5D=&columns%5B0%5D%5Bsearchable%5D=true&columns%5B0%5D%5Borderable%5D=false&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B1%5D%5Bdata%5D=MatNo&columns%5B1%5D%5Bname%5D=&columns%5B1%5D%5Bsearchable%5D=true&columns%5B1%5D%5Borderable%5D=false&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B2%5D%5Bdata%5D=Lot&columns%5B2%5D%5Bname%5D=&columns%5B2%5D%5Bsearchable%5D=true&columns%5B2%5D%5Borderable%5D=false&columns%5B2%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B2%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B3%5D%5Bdata%5D=SerialID&columns%5B3%5D%5Bname%5D=&columns%5B3%5D%5Bsearchable%5D=true&columns%5B3%5D%5Borderable%5D=false&columns%5B3%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B3%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B4%5D%5Bdata%5D=Tester&columns%5B4%5D%5Bname%5D=&columns%5B4%5D%5Bsearchable%5D=true&columns%5B4%5D%5Borderable%5D=false&columns%5B4%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B4%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B5%5D%5Bdata%5D=Result&columns%5B5%5D%5Bname%5D=&columns%5B5%5D%5Bsearchable%5D=true&columns%5B5%5D%5Borderable%5D=false&columns%5B5%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B5%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B6%5D%5Bdata%5D=TestEquipment&columns%5B6%5D%5Bname%5D=&columns%5B6%5D%5Bsearchable%5D=true&columns%5B6%5D%5Borderable%5D=false&columns%5B6%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B6%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B7%5D%5Bdata%5D=TestInstruction&columns%5B7%5D%5Bname%5D=&columns%5B7%5D%5Bsearchable%5D=true&columns%5B7%5D%5Borderable%5D=false&columns%5B7%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B7%5D%5Bsearch%5D%5Bregex%5D=false&start=0&length=10&search%5Bvalue%5D=&search%5Bregex%5D=false&_=1581405486114`

This is the same URL decoded:
`/models/result_overview/?format=datatables&Lot=&MatNo=&Product=&Comment=&Tester=&Result__testDate_min=&Result__testDate_max=&TestEquipment=7500/5: Zwick&TestInstruction=&Result__Tag__name=&draw=9&columns[0][data]=id&columns[0][name]=&columns[0][searchable]=true&columns[0][orderable]=false&columns[0][search][value]=&columns[0][search][regex]=false&columns[1][data]=MatNo&columns[1][name]=&columns[1][searchable]=true&columns[1][orderable]=false&columns[1][search][value]=&columns[1][search][regex]=false&columns[2][data]=Lot&columns[2][name]=&columns[2][searchable]=true&columns[2][orderable]=false&columns[2][search][value]=&columns[2][search][regex]=false&columns[3][data]=SerialID&columns[3][name]=&columns[3][searchable]=true&columns[3][orderable]=false&columns[3][search][value]=&columns[3][search][regex]=false&columns[4][data]=Tester&columns[4][name]=&columns[4][searchable]=true&columns[4][orderable]=false&columns[4][search][value]=&columns[4][search][regex]=false&columns[5][data]=Result&columns[5][name]=&columns[5][searchable]=true&columns[5][orderable]=false&columns[5][search][value]=&columns[5][search][regex]=false&columns[6][data]=TestEquipment&columns[6][name]=&columns[6][searchable]=true&columns[6][orderable]=false&columns[6][search][value]=&columns[6][search][regex]=false&columns[7][data]=TestInstruction&columns[7][name]=&columns[7][searchable]=true&columns[7][orderable]=false&columns[7][search][value]=&columns[7][search][regex]=false&start=0&length=10&search[value]=&search[regex]=false&_=1581405486114`

**Comment by Engensmax** [comment]
This seems to be a general issue with datatables itself:
[https://stackoverflow.com/questions/33862482/datatables-server-side-processing-url-too-long]
I solved it by adding this ajax options in the datatables initiation:
`ajax: {
                            url: "/models/result_overview/?format=datatables" ,// + window.location.href.split('?')[1],
                            data: function(data) {
                                for (var i = 0, len = data.columns.length; i < len; i++) {
                                    delete data.columns[i];
                                }
                            },
                        },`

**Comment by morenoh149** [comment]
ajax seems to have most of the functionality. You'll notice the example uses it https://github.com/izimobil/django-rest-framework-datatables/blob/master/example/albums/templates/albums/albums.html#L65

**Comment by mikejohnsonjr** [comment]
This disables column ordering functions.
