### ISSUE TITLE
How to create the url link ?

### ISSUE THREAD

**Issue by SurendraTamang** [izimobil/django-rest-framework-datatables#78]
How can we give the value of href attribute for creating the link?

**Comment by izimobil** [comment]
Please do not use the issue tracker to ask questions, consult the documentation instead:
https://django-rest-framework-datatables.readthedocs.io/en/latest/

**Comment by BenBlumer** [comment]
It's possible I'm missing something, but I've searched RTD for "href" and "link" and I can't find any examples of this. It would be useful to answer here or include in the docs.

**Comment by BenBlumer** [comment]
Made a pull request to update the documentation. #129
