### ISSUE TITLE
Add HTML/JS examples for django-filter support

### ISSUE THREAD

**Issue by TauPan** [izimobil/django-rest-framework-datatables#79]
It would be great to add a HTML/JS example here.

_Originally posted by @izimobil in https://github.com/izimobil/django-rest-framework-datatables/pull/72_

**Comment by TauPan** [comment]
@izimobil You can assign me. I'm currently working on a different project, but I'll get around to this at some point.

**Comment by vrbrito** [comment]
> @izimobil You can assign me. I'm currently working on a different project, but I'll get around to this at some point.

I'm trying to do a date range filter, could you support that somehow? :)))))

**Comment by TauPan** [comment]
> > @izimobil You can assign me. I'm currently working on a different project, but I'll get around to this at some point.
> 
> I'm trying to do a date range filter, could you support that somehow? :)))))

There is a python example for a date range filter with YADCF in the PR, see https://github.com/izimobil/django-rest-framework-datatables/pull/72#issuecomment-599479938

Unfortunately I'm not able to schedule time to enhance the documentation with HTML + JS examples at the moment. (I was on vacation and now other projects take priority.) And I'm unfortunately not able to share the production code I'm using this in.

I'm using `eonasdan-bootstrap-datetimepicker` with the `moment` js library, if that helps.

An example options entry for yadcf looks like this:
```js
{column_selector: 'changed:name',
       filter_type: 'range_date',
       datepicker_type: 'bootstrap-datetimepicker',
       date_format: 'YYYY-MM-DD HH:mm:ss',
       filter_delay: 1000}
```

**Comment by matthewhegarty** [comment]
Hey guys - thanks for all your efforts in integrating django-filter.  I got it working this weekend and I've updated the [example app](https://github.com/izimobil/django-rest-framework-datatables/pull/91/files) to incorporate what I learnt.  Would welcome any feedback.

**Comment by izimobil** [comment]
@TauPan , @matthewhegarty 0.6.0 is out with your changes, thank you for your patience !

**Comment by alabiad** [comment]
Hello, guys, i'm folloing this topic, can you give me a solution or an example to get date range filter ?
thank you

**Comment by TauPan** [comment]
> Hello, guys, i'm folloing this topic, can you give me a solution or an example to get date range filter ? thank you

Uhm, what about combining the example in https://github.com/izimobil/django-rest-framework-datatables/pull/72#issuecomment-599479938 with the one in https://github.com/izimobil/django-rest-framework-datatables/issues/79#issuecomment-678983450 Does that help?

Unfortunately I won't have time to document give a more elaborate example in the example app.
