### ISSUE TITLE
new django-filter documentation

### ISSUE THREAD

**Issue by slumtrimpet** [izimobil/django-rest-framework-datatables#82]
In the docs:
https://django-rest-framework-datatables.readthedocs.io/en/latest/django-filters.html#django-filter-quickstart

```
class AlbumGlobalFilter(AlbumFilter):
```

AlbumFiltrer is never imported or declared.  Can you please clarify the intended superclass there?

**Comment by izimobil** [comment]
I guess it's a typo and it should have been `GlobalFilter` instead of `AlbumFilter`.
