### ISSUE TITLE
Not Working With @proeprty

### ISSUE THREAD

**Issue by bahaasamoudi** [izimobil/django-rest-framework-datatables#83]
i have this model

> 
    class CachedEvent(models.Model):
          key = models.CharField(max_length=255)
          timestamp = models.DateTimeField()
          eventname = models.CharField(max_length=255)

    @property
    def priority(self):
        eventtype, created = EventType.objects.get_or_create(
            eventname=self.eventname
        )
        return eventtype.priority

viewSet"

> 
    class EventViewSet(viewsets.ReadOnlyModelViewSet):
           queryset = CachedEvent.objects.all()
           serializer_class = CachedEventSerializer

serializer:
> 
    class CachedEventSerializer(serializers.ModelSerializer):
         id = serializers.CharField(source='original_id')

         class Meta:
            model = CachedEvent
            fields = ['key', 'timestamp', 'id', 'eventname', 'priority']

it show error "Cannot resolve keyword 'priority' into field. Choices are: eventname, id, key, timestamp "

**Comment by izimobil** [comment]
You can't use sorting or filtering for dynamic properties, just disable sorting and search for this column in your JS code (see: https://datatables.net/reference/option/columns.orderable and https://datatables.net/reference/option/columns.searchable).

**Comment by morenoh149** [comment]
is it possible to surface a model's @property as a value? not looking to order or sort by this, just extra data for informational purposes.
