### ISSUE TITLE
Update the release

### ISSUE THREAD

**Issue by OmenApps** [izimobil/django-rest-framework-datatables#84]
The current release (0.5.2) does not include the most recent commits, which are required if one wants to use the django_filters integration. The django_filters folder does not get installed unless I pull directly from master.

**Comment by banagale** [comment]
Thanks for this note. I was wondering where this was.

**Comment by Simonefardella** [comment]
Please @izimobil, release the new version with latest changes!

**Comment by Simonefardella** [comment]
@izimobil, any news?

**Comment by slumtrimpet** [comment]
Probably not helping a ton as we all already know this, but in the meantime, we've been forced to do:

`pip install git+https://github.com/izimobil/django-rest-framework-datatables.git`

Because, as you said, the current release is broken if you want to use those documented features.

**Comment by phoebebright** [comment]
I installed using pip install  djangorestframework-datatables then tried to update with pip install git+etc but still didn't get the django_filters directory.  Fixed by doing an uninstall first and then installed from git as suggested by @slumtrimpet
