### ISSUE TITLE
Pagination is not working

### ISSUE THREAD

**Issue by koolfreak** [izimobil/django-rest-framework-datatables#88]
Hi,

I having issue in pagin when i click Next on the datatables it did not go to next page. I have 11 records and 10 per page, when I click 'Next', i have still the same result although in bottom says 'Showing 11 of 11 of 11 entries?

Django==2.2.12
djangorestframework==3.11.0
djangorestframework-datatables==0.5.2

DataTables 1.10.10 
- using ajax: POST

Note: I also notice when i add another record to the DB it did relfect on the list when refresh the browser, but when stop/start the server it reflects.

Thanks

**Comment by mikejohnsonjr** [comment]
I'm having a similar error, I get 50 pages shown by default, even though the top left bar says "Showing 10 entries," and when I click pages 1 thru 5, nothing happens, except when I click page 6, I get the next 50, and so on.

**Comment by CristopherH95** [comment]
Is this happening with `DatatablesPageNumberPagination` or `DatatablesLimitOffsetPagination`, or both?

**Comment by igorexa256** [comment]
Installing via pip does not include the latest changes.

It is solved like this:

1. Remove the package
2. Install `pip install git+https://github.com/izimobil/django-rest-framework-datatables.git`
3. By default we use `DatatablesLimitOffsetPagination`

**Comment by xtlc** [comment]
I have a similar issue:

- Django==3.1.2
- djangorestframework==3.12.2
- djangorestframework-datatables==0.5.2

I have 55 items in the database - pagination offers the following pages:

- 10 -> 6 pages (OK)
- 25 -> 1 page (NOK)
- 50 -> 1 page (NOK)

I already tried unsinistalling and re-installing from git.
