### ISSUE TITLE
limitted format detection

### ISSUE THREAD

**Issue by jerzyk** [izimobil/django-rest-framework-datatables#9]
drf-datatables in the paginator is using a test on 'format' request queryset to switch on/off datatables integration, however DRF allow that format can be specified in 2 ways:
- as a request query variable
- as a suffix

drf-datatables is missing latter one, paginator may have access to this information via the 'view' parameter (`view.format_kwargs` or as a key `kwargs` of the `view.kwargs` dictionary)

`view.kwargs` looks a best option, as it is always there, for the `view.format_kwargs` `hasattr` should be used

format suffix has a precedence over request query variable

last but as well important is that name of the url variable as well as request queryset variable can be overriden specyfing  `FORMAT_SUFFIX_KWARG` and/or `URL_FORMAT_OVERRIDE` - so those options should be used instead hardcoded "format"

**Comment by jerzyk** [comment]
just find out that not only paginators are affected but `DatatablesFilterBackend` has a similar issue

**Comment by izimobil** [comment]
Hello,
Yes I'm aware of that issue, I didn't know about the `view.format_kwargs` variable, thanks for the information.
Since you seem to know well the subject, could you please submit a pull request preferably with tests ?
Thanks.

**Comment by jerzyk** [comment]
slightly different approach - looks like there is already a negotiated renderer - set by DRF, this should too solve an edge case - when user will select only *one* renderer - so no need for format suffix or request variable
