### ISSUE TITLE
Is row selection work ?

### ISSUE THREAD

**Issue by philibe** [izimobil/django-rest-framework-datatables#93]
Hello,

I tried on your example the ability of selection but it doesn't seem to work 

In fact I tried to use django-rest-framework-datatables like this tutorial https://www.gyrocode.com/projects/jquery-datatables-checkboxes/ and the checkbox doesn't work neither.

```javascript
 $('#example').DataTable({
     'select': {
         'style': 'multi'
     },
     'columnDefs': [

         {
             'targets': 1,
             'checkboxes': {
                 'selectRow': true
             }
         }
     ],

 });

```

Do you know if the actual version of  django-rest-framework-datatables can do that ?
These javascript DataTable() options are agnostic for your framework ?

Thank you.

Philippe

PS: I use a lot datatables.net in R Shiny by DT library wrapper, and I try to apply my knowledge for django-rest-framework-datatables.

**Comment by philibe** [comment]
On Flask it works after the installation of  the datatables checkbox js plug-in, that I've forgotten. Maybe it's the only cause and the same thing on Django Rest Framework Datatables

**Comment by izimobil** [comment]
Keep in mind that DRF Datatables is just just a backend adapter for django-rest-framework, your issue seems to be related to the frontend js code...

**Comment by philibe** [comment]
Yes. It seems.
